---
# This playbook contains all actions that will be run on "local" host.
 
# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system
 
# Import docker tasks
- name: Import docker tasks
  include_tasks: docker.yml
 
# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
 
# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system

- import_tasks: install.yml
  tags:
    - system
    - openssl
    - install
    - openssl-install

- import_tasks: config.yml
  tags:
    - system
    - openssl
    - config
    - openssl-config

